# Generated by Django 5.2.7 on 2025-12-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
